networks:
  tm-network:
    driver: bridge

services:
  mysql-db:
      image: mysql:latest
      container_name: mysql-db
      ports:
        - "3306:3306"
        - "33060:33060"
      environment:
        MYSQL_DATABASE: tm_mysql_database
        MYSQL_ROOT_PASSWORD: secret
      volumes:
        - ./dockerSql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
        - db-data:/data/db
      networks:
        - tm-network
  php-apache:
    build: 
      context: .
      dockerfile: DockerFile
    container_name: php-apache
    volumes:
      - ./app:/var/www/html 
      - ./default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./certs/apache-selfsigned.crt:/etc/ssl/certs/apache-selfsigned.crt
      - ./certs/apache-selfsigned.key:/etc/ssl/private/apache-selfsigned.key
      - ./files:/var/www/html/files
      - ./user_storage:/var/www/html/user_storage
      - ./songs:/var/www/html/songs
      - ./films:/var/www/html/films
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /app
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - tm-network  

volumes:
  db-data:
